name: Hasura CI
description: Provides CI/CD for Hasura Metadata/Migrations and Regression Tests
author: Hasura
inputs:
  PATH_TO_HASURA_PROJECT_ROOT:
    required: false
    description: The relative path from the root of your repo to where the Hasura project (containing config.yaml and your migrations/metadata folders) is located. For example, if your top-level directory contains a "hasura" folder, then this value should be ./hasura
  HASURA_CLI_VERSION:
    required: false
    description: Version of Hasura CLI to download and use. Defaults to 'latest' if not set.
  HASURA_ENDPOINT:
    required: false
    description: Optional overriding URL for the Hasura endpoint to call migrate apply and/or regression tests on. Will default to config.yaml value (as the CLI is run from the directory containing config.yaml).
  HASURA_ADMIN_SECRET:
    required: false
    description: Optional overriding admin secret for the Hasura instance. Will default to config.yaml value (as the CLI is run from the directory containing config.yaml).
  HASURA_MIGRATIONS_ENABLED:
    required: false
    description: Whether or not migrations should be run during CI/CD.
  HASURA_REGRESSION_TESTS_ENABLED:
    required: false
    description: Whether or not the CI/CD should attempt to run regression tests. Only available for Hasura Cloud and Hasura Enterprise users.
  HASURA_REGRESSION_TESTSUITE_ID:
    required: false
    description: The ID for the regression testsuite to run, if enabled.
  HASURA_PERSONAL_ACCESS_TOKEN:
    required: false
    description: A Personal Access Token
  HASURA_PROJECT_ID:
    required: false
    description: ID for the Hasura Cloud or Hasura Enterprise project to run regression tests on, if enabled
runs:
  using: docker
  image: ./Dockerfile
